# Generated by Django 5.2 on 2025-04-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eshmerko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='update',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='program_versions/'),
        ),
        migrations.AddField(
            model_name='update',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
