# Generated by Django 5.2 on 2025-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eshmerko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_id', models.UUIDField(unique=True)),
                ('app_name', models.CharField(max_length=100)),
                ('app_version', models.CharField(max_length=20)),
                ('system_platform', models.CharField(max_length=50)),
                ('python_version', models.CharField(max_length=20)),
                ('first_launch', models.DateTimeField(auto_now_add=True)),
                ('last_launch', models.DateTimeField(auto_now=True)),
                ('launch_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Лог запуска программы',
                'verbose_name_plural': 'Логи запусков программ',
                'indexes': [models.Index(fields=['install_id'], name='app_eshmerk_install_16dce8_idx'), models.Index(fields=['app_name'], name='app_eshmerk_app_nam_435c35_idx')],
            },
        ),
    ]
