# Generated by Django 5.2 on 2025-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eshmerko', '0002_programlaunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlaunch',
            name='python_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Версия Python'),
        ),
        migrations.AlterField(
            model_name='programlaunch',
            name='system_platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Операционная система'),
        ),
    ]
