# Generated by Django 5.2 on 2025-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eshmerko', '0003_alter_programlaunch_python_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programlaunch',
            options={'ordering': ['-last_launch'], 'verbose_name': 'Лог запуска программы', 'verbose_name_plural': 'Логи запусков программ'},
        ),
        migrations.RemoveIndex(
            model_name='programlaunch',
            name='app_eshmerk_install_16dce8_idx',
        ),
        migrations.RemoveIndex(
            model_name='programlaunch',
            name='app_eshmerk_app_nam_435c35_idx',
        ),
        migrations.AddIndex(
            model_name='programlaunch',
            index=models.Index(fields=['last_launch'], name='app_eshmerk_last_la_49f17c_idx'),
        ),
        migrations.AddIndex(
            model_name='programlaunch',
            index=models.Index(fields=['app_name', 'app_version'], name='app_eshmerk_app_nam_1cd786_idx'),
        ),
    ]
