# Generated by Django 5.1.1 on 2025-05-06 16:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eshmerko', '0004_project_projectimage_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Краткое описание'),
        ),
    ]
